# Ensure apps build and tests pass

name: Build

on:
  pull_request:
    branches: [master, dev]

jobs:
  build-frontend:
    name: Build Frontend App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Build node app
        working-directory: frontend
        env:
          CI: true
        run: |
          npm ci
          npm run init
          npm run build

  build-firebase:
    name: Build Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        working-directory: cloud-functions/functions
        run: npm install
      - name: Initialize config files
        working-directory: cloud-functions/functions
        run: npm run init
      - name: Setup functions config
        working-directory: cloud-functions/functions
        run: npm run config:set
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          NODE_ENV: test
          VERIFICATION_SERVER_API_KEY: ${{ secrets.VERIFICATION_SERVER_API_KEY }}
          VERIFICATION_SERVER_URL: ${{ secrets.VERIFICATION_SERVER_URL }}
      - name: Lint and Build
        working-directory: cloud-functions/functions
        run: |
          npm run lint
          npm run build
      - name: Remove node_modules for upload
        working-directory: cloud-functions/functions
        run: rm -r node_modules
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: cloud-functions-artifact
          path: cloud-functions/functions

  deploy-firebase:
    name: Deploy Firebase
    needs: build-firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: cloud-functions-artifact
          path: cloud-functions/functions
      - name: Install
        working-directory: cloud-functions/functions
        run: npm install
      - name: Deploy to Firebase Test Infra
        uses: w9jds/firebase-action@master
        with:
          args: deploy -f --project=test
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: cloud-functions/

  firebase-tests:
    name: Run Firebase Tests
    needs: deploy-firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: cloud-functions-artifact
          path: cloud-functions/functions
      - name: Install
        working-directory: cloud-functions/functions
        run: npm install
      - name: Run Tests
        working-directory: cloud-functions/functions
        run: npm run test_ci
        env:
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  frontend-tests:
    name: Run Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        working-directory: frontend
        run: npm install
      - name: Run Tests
        working-directory: frontend
        env:
          CI: true
        run: npm run test_ci
