# Builds node app and deploys to AWS S3
# 'dev' branch deploys to staging - http://permissions-staging.s3-website-us-west-1.amazonaws.com/

# TO ADD AT SOME POINT: prod branch deploy to production

name: Deploy

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Build node app
        working-directory: permission-portal-frontend
        env:
          CI: true
        run: |
          npm ci
          npm run init
          npm run build:staging

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to S3
        working-directory: permission-portal-frontend
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh
