# Builds node app and deploys to AWS S3
# Builds and tests firebase and deploys to staging / prod

name: Deploy

on:
  push:
    branches: [dev, master]

jobs:
  deploy-frontend:
    Name: Build and Deploy Frontend App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Build node app for staging
        if: github.ref == 'refs/heads/dev'
        working-directory: permission-portal-frontend
        env:
          CI: true
        run: |
          npm ci
          npm run init
          npm run git-info
          npm run build:staging

      - name: Build node app for prod
        if: github.ref == 'refs/heads/master'
        working-directory: permission-portal-frontend
        env:
          CI: true
        run: |
          npm ci
          npm run init
          npm run git-info
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to S3
        working-directory: permission-portal-frontend
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh

  deploy-firebase:
    name: Build, Test, and Deploy Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        working-directory: permission-portal-cloud-functions/functions
        run: npm install

      - name: Initialize config files
        working-directory: permission-portal-cloud-functions/functions
        run: npm run init        

      - name: Build and Deploy to Firebase Test Infra
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project=test
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_TEST }}
          PROJECT_PATH: permission-portal-cloud-functions/

      - name: Run Tests
        working-directory: permission-portal-cloud-functions/functions
        run: npm run test_ci
        env:
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_TEST }}

      - name: Build and Deploy to Firebase Staging Infra
        if: github.ref == 'refs/heads/dev'
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project=staging
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_STAGING }}
          PROJECT_PATH: permission-portal-cloud-functions/
          NODE_ENV: staging

      - name: Build and Deploy to Firebase Prod Infra
        if: github.ref == 'refs/heads/master'
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project=prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PROD }}
          PROJECT_PATH: permission-portal-cloud-functions/
          NODE_ENV: prod
