# To ensure the code works on other platforms than the 1.13 linux target we run a full
# matrix of targets only when merging into master
name: CI master
on:
  push:
    branches:
      - "master"

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: cd report-service/functions && go test ./...
