# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master, dev ]

jobs:
  main:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: cd cloud-functions/functions/ && npm run build
    - name: Deploy to Firebase
      run: cd cloud-functions/functions && firebase deploy --project=test
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
