# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master, dev ]

jobs:
  main:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: cloud-functions/functions
      run: npm run build
    - name: Deploy to Firebase
      working-directory: cloud-functions/functions
      run: firebase deploy --project=test
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
